### PR TITLE
PHP 8: Fixed archive import from Amazon S3

### LINKED ISSUE #27: S3 Import: Fatal error while importing under PHP 8

### PR DESCRIPTION
**Pull request by tampe125**
Close #27

### CODE REVIEW

File: source/s3/s3.connector.php [hunk 1]
```diff
@@ -87,8 +87,7 @@ public function getObject($bucket, $uri, $saveTo = false, $from = null, $to = nu
         {
             throw new AKS3CannotGetFile(
                 sprintf(__METHOD__ . "({$bucket}, {$uri}): [%s] %s\n\nDebug info:\n%s",
-                    $response->error->getCode(), $response->error->getMessage(), print_r($response->body, true)),
-                $response->error->getCode()
+                    $response->error->getCode(), $response->error->getMessage(), print_r($response->body, true))
```
Comment (nikosdion) [inline source/s3/s3.connector.php:90]: Since we're doing this, can you please put $bucket and $uri as `sprintf` variables?

File: source/urlimport/feature.urlimport.php [hunk 2]
```diff
@@ -545,7 +545,13 @@ public function onLoadTranslations()
 	 */
 	protected function formatByteSize($size)
 	{
+        if (!$size)
```
Comment (nikosdion) [inline source/urlimport/feature.urlimport.php:548]: I'd prefer doing it differently:
```php
$size = (int)($size ?: 0)
```
The Elvis operator is available since PHP 5.3. The above is equivalent to writing:
```php
$size = (int)(empty($size) ? 0 : $size);
```

File: source/s3/s3.connector.php (hunk 1 above)
Comment (nikosdion) [reply source/s3/s3.connector.php:90]: BTW, can you also make a PR to https://github.com/akeeba/s3/blob/development/src/Connector.php so the changes sync to all our software?

**Review by nikosdion — CHANGES_REQUESTED** [review]

File: source/urlimport/feature.urlimport.php (hunk 2 above)
Comment (tampe125) [reply source/urlimport/feature.urlimport.php:548]: mhm... no, that's different. The problem is that $size is 0 and then the following operation raises a fatal error. So if we have anything that will be cast to 0, we have to return early instead of going with the log/pow steps.
